// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Zu4K3hesRQjcscWm73rqXagoHeCS1ik',
    appId: '1:845859954756:web:82e7691ec31e97d58a9c11',
    messagingSenderId: '845859954756',
    projectId: 'chatappfirebase-445c1',
    authDomain: 'chatappfirebase-445c1.firebaseapp.com',
    storageBucket: 'chatappfirebase-445c1.appspot.com',
    measurementId: 'G-XKVFG1PG36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmKGTFkinja9ytgZhtQHEKSKPKGYTRwzU',
    appId: '1:845859954756:android:67b3e5be37ee075f8a9c11',
    messagingSenderId: '845859954756',
    projectId: 'chatappfirebase-445c1',
    storageBucket: 'chatappfirebase-445c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRmf26ODDkjuTAfzX5NX8vNi-DyDQZMko',
    appId: '1:845859954756:ios:38459470f32f69f08a9c11',
    messagingSenderId: '845859954756',
    projectId: 'chatappfirebase-445c1',
    storageBucket: 'chatappfirebase-445c1.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRmf26ODDkjuTAfzX5NX8vNi-DyDQZMko',
    appId: '1:845859954756:ios:0848adc9f56076a38a9c11',
    messagingSenderId: '845859954756',
    projectId: 'chatappfirebase-445c1',
    storageBucket: 'chatappfirebase-445c1.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
